### ISSUE TITLE
Incorrect Colour Assignment on Tab Curves

### ISSUE THREAD

**Issue by lazerl0rd** [coekuss/quietfox#4]
An example is shown below. This is Firefox 72 on Debian 10 Linux (KDE Plasma - X11).

![Screenshot_20200218_203728](https://user-images.githubusercontent.com/24303423/74775948-982ad900-528e-11ea-95b5-e0adc2c07934.png)

**Comment by coekuss** [comment]
This happens when your Firefox theme has some transparency in the toolbar, because the little blocks that generate the rounded corners layer on top of your tab, and the two transparencies interact to make it appear a different color. Some linux distros are like this on the default theme, but it should be fixed by using the built-in Light or Dark theme, or getting another theme
