### ISSUE TITLE
Transparent context menu

### ISSUE THREAD

**Issue by prediscover** [coekuss/quietfox#7]
Love the theme. So clean and animations are so smooth!

Something that makes it unusable though. the context menus are completely transparent! 
I'm using your .CSS file straight from GitHub, I have no other customization applied. 

FF Version: 76.0b5
OS: Win 10 19608

Screenshot: 
![image](https://user-images.githubusercontent.com/10902462/79606777-f87ba280-80a6-11ea-9e32-9d7f2ce86924.png)

**Comment by coekuss** [comment]
Yes this is currently happening in Firefox Beta since i've only been releasing Quietfox for Firefox Stable. However, most updates from Firefox Beta eventually come to Stable, so I've whipped up a quick fix. 

It looks like they renamed all classes `popup-internal-box` to `menupopup-arrowscrollbox`, so you can open your userChrome.css and replace all instances of `popup-internal-box` with `menupopup-arrowscrollbox` and your menus should come back

**Comment by prediscover** [comment]
ah, definitely my fault for using on beta release. 

Yep your suggestion worked like a charm.
