### ISSUE TITLE
Tab top shadow when window out of focus

### ISSUE THREAD

**Issue by prediscover** [coekuss/quietfox#8]
Not sure if this is fixable (or even an issue) but I notice on the light theme on firefox there is no top shadow on MacOS. I don't think this happens on windows. It looks kind of odd with it being such low contrast. Feel free to deem this a non-issue.

This is with the Window out of focus:
<img width="509" alt="image" src="https://user-images.githubusercontent.com/10902462/80413819-e8bd4480-8884-11ea-99aa-9aad34d5555d.png">
Window in focus:
<img width="512" alt="image" src="https://user-images.githubusercontent.com/10902462/80414068-4b164500-8885-11ea-87e6-915fe16190c7.png">

**Comment by coekuss** [comment]
Ah this is something I was running into while initially building quietfox. I wasn't able to get a top shadow to look right because Firefox seems to insist that the space above the tabs stays a solid color, so the top shadow would get cropped off when I tried to apply it. I will take another look at this though, since Firefox might have updated how it works
